#!/usr/bin/env node
/**
 * Downloads the deck's three typefaces and inlines them into css/fonts.css as
 * base64 data URIs.
 *
 * Two reasons this is a build step rather than a <link>:
 *   1. The deck is presented from file:// in a conference room. No wifi.
 *   2. The published Artifact's CSP blocks font CDNs outright, so a linked
 *      webfont would fall back silently and the deck would render in Times.
 *
 * The typography carries the deck's central idea, so a silent fallback would
 * cost real meaning:
 *   Newsreader (serif)  — what a human says
 *   IBM Plex Mono       — what the machine sees
 *   IBM Plex Sans       — neutral connective tissue
 *
 *   node tools/fetch-fonts.mjs
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CDN = "https://cdn.jsdelivr.net/npm";

const FACES = [
  { family: "Newsreader", weight: 400, style: "normal", pkg: "newsreader", file: "newsreader-latin-400-normal" },
  { family: "Newsreader", weight: 600, style: "normal", pkg: "newsreader", file: "newsreader-latin-600-normal" },
  { family: "Newsreader", weight: 400, style: "italic", pkg: "newsreader", file: "newsreader-latin-400-italic" },
  { family: "Plex Sans", weight: 400, style: "normal", pkg: "ibm-plex-sans", file: "ibm-plex-sans-latin-400-normal" },
  { family: "Plex Sans", weight: 600, style: "normal", pkg: "ibm-plex-sans", file: "ibm-plex-sans-latin-600-normal" },
  { family: "Plex Mono", weight: 400, style: "normal", pkg: "ibm-plex-mono", file: "ibm-plex-mono-latin-400-normal" },
  { family: "Plex Mono", weight: 500, style: "normal", pkg: "ibm-plex-mono", file: "ibm-plex-mono-latin-500-normal" },
];

console.log("Building inlined font stylesheet");

const blocks = await Promise.all(
  FACES.map(async (face) => {
    const url = `${CDN}/@fontsource/${face.pkg}/files/${face.file}.woff2`;
    const res = await fetch(url, { redirect: "follow" });
    if (!res.ok) throw new Error(`${face.file}: HTTP ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    console.log(`  ${face.file.padEnd(36)} ${(buf.length / 1024).toFixed(0)} KB`);

    return `@font-face {
  font-family: "${face.family}";
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: block;
  src: url(data:font/woff2;base64,${buf.toString("base64")}) format("woff2");
}`;
  })
);

const out = `/* GENERATED by tools/fetch-fonts.mjs — do not edit by hand.
   Fonts are inlined as data URIs so the deck works offline from file://
   and survives the Artifact CSP, which blocks external font requests.
   Newsreader + IBM Plex are both SIL Open Font License 1.1. */

${blocks.join("\n\n")}
`;

mkdirSync(resolve(ROOT, "css"), { recursive: true });
writeFileSync(resolve(ROOT, "css/fonts.css"), out);
console.log(`\n  wrote css/fonts.css (${(out.length / 1024).toFixed(0)} KB)`);
