#!/usr/bin/env node
/**
 * Downloads the real GPT-2 byte-level BPE tokenizer files and emits data/bpe.js.
 *
 * Why a build step: the deck is presented from file://, where fetch() of local
 * files is blocked by CORS. So the vocab has to arrive as a plain script that
 * assigns globals, not as JSON loaded at runtime.
 *
 * Why the full merge list (no trimming): trimming merges silently changes how
 * words split, and this deck makes the claim "these are the real token IDs."
 * ~1.5MB of string is a fine price for that being true.
 *
 * Storage format: vocab is stored as tokens newline-joined in id order (id ===
 * line index), which is far smaller than the original token->id JSON object.
 * GPT-2's byte-level alphabet never contains a newline, so the join is safe.
 *
 *   node tools/fetch-vocab.mjs
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const BASE = "https://huggingface.co/openai-community/gpt2/resolve/main";

async function get(name) {
  const url = `${BASE}/${name}`;
  process.stdout.write(`  fetching ${name} ... `);
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
  const text = await res.text();
  console.log(`${(text.length / 1024).toFixed(0)} KB`);
  return text;
}

console.log("Building GPT-2 tokenizer data");

const [vocabRaw, mergesRaw] = await Promise.all([
  get("vocab.json"),
  get("merges.txt"),
]);

const vocab = JSON.parse(vocabRaw);
const size = Object.keys(vocab).length;

// Re-order token -> id map into an id-indexed array.
const byId = new Array(size);
for (const [token, id] of Object.entries(vocab)) byId[id] = token;
for (let i = 0; i < size; i++) {
  if (byId[i] === undefined) throw new Error(`vocab has a hole at id ${i}`);
  if (byId[i].includes("\n")) throw new Error(`token ${i} contains a newline`);
}

// merges.txt opens with a "#version:" comment line; drop it and any blanks.
const merges = mergesRaw
  .split("\n")
  .slice(1)
  .filter((line) => line.trim().length > 0);

const out = `// GENERATED by tools/fetch-vocab.mjs — do not edit by hand.
// Real GPT-2 byte-level BPE: ${size} tokens, ${merges.length} merges.
// Source: ${BASE}
// Loaded as a global because the deck runs from file:// (no fetch, no modules).
window.BPE_VOCAB = ${JSON.stringify(byId.join("\n"))};
window.BPE_MERGES = ${JSON.stringify(merges.join("\n"))};
`;

mkdirSync(resolve(ROOT, "data"), { recursive: true });
const dest = resolve(ROOT, "data/bpe.js");
writeFileSync(dest, out);

console.log(`\n  ${size} tokens, ${merges.length} merges`);
console.log(`  wrote data/bpe.js (${(out.length / 1024 / 1024).toFixed(2)} MB)`);
